# Generated by Django 2.1.7 on 2019-04-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '재구매 의사 없어요(1점)'), (2, '별로에요(2점)'), (3, '나쁘지 않아요(3점)'), (4, '구매 의사 있어요(4점)'), (5, '주변 사람에게 추천해요(5점)')], default=1),
        ),
    ]
