# Generated by Django 2.2 on 2019-04-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-pk'], 'verbose_name': '장바구니', 'verbose_name_plural': '장바구니 목록'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '카테고리', 'verbose_name_plural': '카테고리 목록'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글 목록'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-pk'], 'verbose_name': '회사', 'verbose_name_plural': '회사 목록'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk'], 'verbose_name': '판매상품', 'verbose_name_plural': '판매상품 목록'},
        ),
    ]
