# Generated by Django 2.2 on 2019-04-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-pk'], 'verbose_name': '사용자', 'verbose_name_plural': '사용자 목록'},
        ),
    ]
