# Generated by Django 2.2 on 2019-04-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentquestion',
            options={'ordering': ['-pk'], 'verbose_name': '질문게시판 댓글', 'verbose_name_plural': '질문게시판 댓글 목록'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pk'], 'verbose_name': '질문게시판', 'verbose_name_plural': '질문게시판 목록'},
        ),
    ]
