# Generated by Django 2.2 on 2019-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_commentcommunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcommunity',
            name='image',
            field=models.ImageField(null=True, upload_to='community'),
        ),
    ]
