# Generated by Django 2.1.7 on 2019-05-11 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20190510_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.Question'),
        ),
    ]
