# Generated by Django 2.1.7 on 2019-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_commentquestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentquestion',
            name='like',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
