# Generated by Django 2.1.7 on 2019-05-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20190516_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentquestion',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
